apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-sa
  annotations:
    serving.kserve.io/s3-endpoint: 10.43.207.237:9000 # replace with your s3 endpoint 
    serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
    serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
