# 对应的 Service 配置（如果需要暴露服务）
apiVersion: v1
kind: Service
metadata:
  name: yolo-web-service
spec:
  selector:
    app: yolo-web
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP  # 或者 NodePort/LoadBalancer
